language: csharp
solution: NexusParser.sln
dotnet: 2.1
mono: none
before_install:
  - dotnet tool install --tool-path="./coverlet/" coverlet.console
  - cd NexusParser
  - wget http://www.antlr.org/download/antlr-4.7.1-complete.jar
  - sh antlr.sh
  - cd ..
script:
  - dotnet restore
  - dotnet build
  - dotnet test NexusParserTest/NexusParserTest.csproj
after_success:
  - ./coverlet/coverlet NexusParserTest/bin/Debug/netcoreapp2.1/NexusParserTest.dll --target "dotnet" --targetargs "test NexusParserTest/NexusParserTest.csproj --no-build" --format opencover
  - bash <(curl -s https://codecov.io/bash)
