language: csharp
solution: NexusParser.sln
dotnet: 2.1
install:
  - nuget restore NexusParser.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - dotnet build
  - dotnet test
