language: csharp
solution: NexusParser.sln
dotnet: 2.1
mono: none
before_install:
  - cd NexusParser
  - wget http://www.antlr.org/download/antlr-4.7.1-complete.jar
  - sh antlr.sh
  - cd ..
script:
  - dotnet restore
  - dotnet build
  - dotnet test NexusParserTest/NexusParserTest.csproj
after_success:
  - coveralls
