language: csharp
solution: NexusParser.sln
dotnet: 2.1
mono: none
before_install:
  - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.3/codacy-coverage-reporter-4.0.3-assembly.jar
  - dotnet tool install --tool-path="./coverlet/" coverlet.console
  - cd NexusParser
  - wget http://www.antlr.org/download/antlr-4.7.2-complete.jar
  - sh antlr.sh
  - cd ..
script:
  - dotnet restore
  - dotnet build
  - dotnet test NexusParserTest/NexusParserTest.csproj
after_success:
  - ./coverlet/coverlet NexusParserTest/bin/Debug/netcoreapp2.1/NexusParserTest.dll --target "dotnet" --targetargs "test NexusParserTest/NexusParserTest.csproj --no-build" --format opencover
  - ./coverlet/coverlet NexusParserTest/bin/Debug/netcoreapp2.1/NexusParserTest.dll --target "dotnet" --targetargs "test NexusParserTest/NexusParserTest.csproj --no-build" --format cobertura
  - bash <(curl -s https://codecov.io/bash)
  - java -jar codacy-coverage-reporter-4.0.3-assembly.jar report -l CSharp -r coverage.cobertura.xml --commit-uuid $TRAVIS_COMMIT
