//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Nexus.gp4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="INexusListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class NexusBaseListener : INexusListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.file_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile_declaration([NotNull] NexusParser.File_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.file_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile_declaration([NotNull] NexusParser.File_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] NexusParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] NexusParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.class"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass([NotNull] NexusParser.ClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.class"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass([NotNull] NexusParser.ClassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.class_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_member([NotNull] NexusParser.Class_memberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.class_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_member([NotNull] NexusParser.Class_memberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>namedType</c>
	/// labeled alternative in <see cref="NexusParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedType([NotNull] NexusParser.NamedTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>namedType</c>
	/// labeled alternative in <see cref="NexusParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedType([NotNull] NexusParser.NamedTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>tupleType</c>
	/// labeled alternative in <see cref="NexusParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTupleType([NotNull] NexusParser.TupleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>tupleType</c>
	/// labeled alternative in <see cref="NexusParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTupleType([NotNull] NexusParser.TupleTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>mapType</c>
	/// labeled alternative in <see cref="NexusParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapType([NotNull] NexusParser.MapTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>mapType</c>
	/// labeled alternative in <see cref="NexusParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapType([NotNull] NexusParser.MapTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.variable_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_declaration([NotNull] NexusParser.Variable_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.variable_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_declaration([NotNull] NexusParser.Variable_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.function_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_parameter([NotNull] NexusParser.Function_parameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.function_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_parameter([NotNull] NexusParser.Function_parameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.function_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_declaration([NotNull] NexusParser.Function_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.function_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_declaration([NotNull] NexusParser.Function_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.assignment_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_statement([NotNull] NexusParser.Assignment_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.assignment_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_statement([NotNull] NexusParser.Assignment_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_statement([NotNull] NexusParser.Return_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.return_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_statement([NotNull] NexusParser.Return_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.variable_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_statement([NotNull] NexusParser.Variable_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.variable_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_statement([NotNull] NexusParser.Variable_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] NexusParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] NexusParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_statement([NotNull] NexusParser.While_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.while_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_statement([NotNull] NexusParser.While_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.for_init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_init([NotNull] NexusParser.For_initContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.for_init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_init([NotNull] NexusParser.For_initContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.for_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_statement([NotNull] NexusParser.For_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.for_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_statement([NotNull] NexusParser.For_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.function_call_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_call_statement([NotNull] NexusParser.Function_call_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.function_call_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_call_statement([NotNull] NexusParser.Function_call_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.function_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_body([NotNull] NexusParser.Function_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.function_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_body([NotNull] NexusParser.Function_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.function_body_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_body_statement([NotNull] NexusParser.Function_body_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.function_body_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_body_statement([NotNull] NexusParser.Function_body_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] NexusParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] NexusParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolean([NotNull] NexusParser.BooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.boolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolean([NotNull] NexusParser.BooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.array_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_access([NotNull] NexusParser.Array_accessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.array_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_access([NotNull] NexusParser.Array_accessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] NexusParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] NexusParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.quoted_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuoted_text([NotNull] NexusParser.Quoted_textContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.quoted_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuoted_text([NotNull] NexusParser.Quoted_textContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] NexusParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] NexusParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] NexusParser.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] NexusParser.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.extension_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtension_function([NotNull] NexusParser.Extension_functionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.extension_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtension_function([NotNull] NexusParser.Extension_functionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
