//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Nexus.gp4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="NexusParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface INexusListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.file_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile_declaration([NotNull] NexusParser.File_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.file_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile_declaration([NotNull] NexusParser.File_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] NexusParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] NexusParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass([NotNull] NexusParser.ClassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass([NotNull] NexusParser.ClassContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.class_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_member([NotNull] NexusParser.Class_memberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.class_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_member([NotNull] NexusParser.Class_memberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.tuple_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple_declaration([NotNull] NexusParser.Tuple_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.tuple_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple_declaration([NotNull] NexusParser.Tuple_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] NexusParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] NexusParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_declaration([NotNull] NexusParser.Variable_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_declaration([NotNull] NexusParser.Variable_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.function_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_parameter([NotNull] NexusParser.Function_parameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.function_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_parameter([NotNull] NexusParser.Function_parameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_declaration([NotNull] NexusParser.Function_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_declaration([NotNull] NexusParser.Function_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_statement([NotNull] NexusParser.Assignment_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_statement([NotNull] NexusParser.Assignment_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_statement([NotNull] NexusParser.Return_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_statement([NotNull] NexusParser.Return_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.variable_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_statement([NotNull] NexusParser.Variable_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.variable_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_statement([NotNull] NexusParser.Variable_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] NexusParser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] NexusParser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_statement([NotNull] NexusParser.While_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.while_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_statement([NotNull] NexusParser.While_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.for_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_init([NotNull] NexusParser.For_initContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.for_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_init([NotNull] NexusParser.For_initContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.for_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_statement([NotNull] NexusParser.For_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.for_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_statement([NotNull] NexusParser.For_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.function_call_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call_statement([NotNull] NexusParser.Function_call_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.function_call_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call_statement([NotNull] NexusParser.Function_call_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_body([NotNull] NexusParser.Function_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_body([NotNull] NexusParser.Function_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] NexusParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] NexusParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean([NotNull] NexusParser.BooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean([NotNull] NexusParser.BooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.array_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_access([NotNull] NexusParser.Array_accessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.array_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_access([NotNull] NexusParser.Array_accessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] NexusParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] NexusParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] NexusParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] NexusParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] NexusParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] NexusParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NexusParser.extension_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtension_function([NotNull] NexusParser.Extension_functionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NexusParser.extension_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtension_function([NotNull] NexusParser.Extension_functionContext context);
}
